export const colordata = [
    { color: '#ce2a2a' },
    { color: '#1372a6' },
    { color: 'green' },
    { color: '#b9b924' },
    { color: 'purple' },
    { color: '#7a15bd' },
    { color: 'brown' },
    { color: 'darkgreen' },
    { color: 'voilent' },
    { color: 'red' },
    { color: 'red' },
    { color: 'red' },
    { color: 'red' },
    { color: 'red' },
    { color: 'red' },
    { color: 'red' },
    { color: 'red' },
    { color: 'red' },
]